# Generated by Django 3.2.16 on 2023-09-08 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230904_1726'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('sorting_posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.location', verbose_name='Местоположение'),
        ),
    ]
